Jd/vuetify front end pages
onebeyond/onebeyond-studio-obelisk pull request #15
Opened 2023-02-21 10:44 UTC by jamieDavisOneBeyond

2023-02-27 09:16 UTC, fabiomaistro submitted a review, later dismissed
I believe this is not ready for a review yet

2023-02-27 15:42 UTC, jamieDavisOneBeyond commented
I've had a look through, it should be ready now I think? Unless I've missed some obvious things from previous work done

2023-02-28 11:08 UTC, andriikaplanovskyi requested changes

2023-02-28 11:08 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.Domain/Features/Users/Commands/RequestResetPasswordDto.cs
> +namespace OneBeyond.Studio.Obelisk.Domain.Features.Users.Commands;
Why all those Dtos are in Commands namespace?

2023-02-28 11:08 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/TFAController.cs
> +    private readonly UserContext _userContext;
That looks very strange, we inject UserContext into a controller, which everyone can access, even non-authenticated users.

2023-02-28 11:08 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/TFAController.cs
> +public class TFAController : ControllerBase
sealed

2023-02-28 11:08 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/UserAccountController.cs
> +    [HttpPost("ChangePassword")]
move to AuthController?

2023-02-28 11:14 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Domain/ChangePasswordResult.cs
> +        => new($"Login with id {loginId} not found");
These errors are quite unlikely and, at the moment, we don't show them in the front-end... It depends on what you believe it's better when this API is called, for example, from `Swagger`. But is it really something we want to carry about?

2023-02-28 11:14 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Domain/ChangePasswordResult.cs
> +        => new($"Login has no a password yet, use SetPassword to set it");
Agree, please change

2023-02-28 11:14 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Domain/ChangePasswordResult.cs
> +        => new($"Login with id {loginId} not found");
It would be an issue for reset password, but not for the change password: the users are authenticated to change their own password.

2023-02-28 11:15 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/UserAccountController.cs
> +    public async Task<ChangePasswordResult> ChangePassword([FromBody] ChangePassword changePassword, CancellationToken cancellationToken)
This is wrong!

2023-02-28 11:15 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/UserAccountController.cs
> +        changePassword.AttachLoginId(HttpContext.User?.Identity?.TryGetLoginId() ?? string.Empty);
I agree, I was thinking the same (Dto vs Command)

2023-02-28 11:15 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.Domain/Features/Users/Commands/ResetPasswordDto.cs
> +    public string? UserName { get; set; }
Agree, please change

2023-02-28 11:16 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/TFAController.cs
> +    private readonly UserContext _userContext;
@jamieDavisOneBeyond Can you clarify?

2023-02-28 11:23 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Domain/ChangePasswordResult.cs
> +        => new($"Login with id {loginId} not found");
> But is it really something we want to carry about?
What exactly: status codes of error messages or their localization?

2023-02-28 11:25 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Domain/ChangePasswordResult.cs
> +        => new($"Login with id {loginId} not found");
*care about, sorry...
Yeah, I meant both, I wouldn't worry about localization and they are 3 messages, do we need to bring the complexity of a status code? Not sure...

2023-02-28 11:26 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Domain/ChangePasswordResult.cs
> +        => new($"Login with id {loginId} not found");
If users are authenticated when they change their password, how can we get those messages?

![image](https://user-images.githubusercontent.com/120190898/221840475-be9e2c23-3020-4385-9cc6-d8752b337d1d.png)

2023-02-28 11:33 UTC, jamieDavisOneBeyond commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/TFAController.cs
> +    private readonly UserContext _userContext;
Yeah he's right this should be authenticated users only, will change this

2023-02-28 11:34 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Domain/ChangePasswordResult.cs
> +        => new($"Login with id {loginId} not found");
No worries. I'm "painting" atm, will let you know as soon I push my version, we'll discuss.

2023-02-28 11:34 UTC, jamieDavisOneBeyond commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/UserAccountController.cs
> +    [HttpPost("ChangePassword")]
If I was to guess (this was previous work) this is where an admin can change a users password not when they're logging in (like forgotten password), so I think this should stay?

2023-02-28 11:35 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/TFAController.cs
> +    private readonly UserContext _userContext;
@jamieDavisOneBeyond pls do not change anything in the branch atm, I'm trying to clean the code a little bit, will let you know as soon as I finish.

2023-02-28 11:37 UTC, jamieDavisOneBeyond commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/TFAController.cs
> +    private readonly UserContext _userContext;
Sure ^

2023-02-28 11:37 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/UserAccountController.cs
> +    [HttpPost("ChangePassword")]
@jamieDavisOneBeyond Jamie, I think admins can't change users' passwords. They can only reset them. Can you confirm pls before I destroy everything?

2023-02-28 11:40 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/UserAccountController.cs
> +    [HttpPost("ChangePassword")]
Correct Andrii, admins can ONLY force a reset password...

2023-02-28 12:10 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/UserAccountController.cs
> +    [HttpPost("ChangePassword")]
Yes, but that is when they are authenticated... That is the default option that every user has (to change their own password). But if you go to the "Users" page as an admin, you can only force the reset password of other users, you can't change their password :D

2023-02-28 12:30 UTC, jamieDavisOneBeyond commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/UserAccountController.cs
> +    [HttpPost("ChangePassword")]
Yeah I'm not sure what the thought process was behind this, it's all assumptions as the code was written before I started working on this

2023-02-28 13:09 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.WebApi/Helpers/AppLinkGenerator.cs
> -        var url = _linkGenerator.GetUriByPage(
@jamieDavisOneBeyond  may I ask you to have a look please. In the original Waterloo when a user is created, we send them a link to **Set** Password Page, where they can set their new pawssword. After that, a user can only **reset** their password. To support this logic, In WebAPI -> ClientApplicationLinkGenerator, we have two methods: GetSetPasswordUrl and GetResetPasswordUrl approperiately. Something makes me think that **set** password logic is not supported in the new  Vuetify Front End. 
cc @fabiomaistro

2023-02-28 16:15 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/TFAController.cs
> +public sealed class TFAController : ControllerBase
@jamieDavisOneBeyond Jamie, I modified the TFAController, could you please check the UI part 

https://dev.azure.com/onebeyondinternal/Obelisk/_git/Vuetify%20Front%20End?path=/OneBeyond.Studio.Obelisk.WebUI/src/components/admin/tfa

and adjus the logic to the new controller? If there are any questions or something is not clear - please let me know. 

cc @fabiomaistro 

Also, guys, not sure why TFA components are in admin folder, as I thought users can switch TFA on / off  for their accounts in Waterloo.

2023-02-28 16:17 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.WebApi/Controllers/TFAController.cs
> +    public Task<LoginTfaSettings> GetTfaSettings(CancellationToken cancellationToken)
Also, @jamieDavisOneBeyond, may I ask you to have a look at UserController:

![image](https://user-images.githubusercontent.com/120190898/221912876-2a3f4d25-b993-4be4-8245-d79c970197ce.png)

and to add summaries to all TFA controller methods. That's what Swagger will show in its documentation. 

cc @fabiomaistro

2023-02-28 17:33 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.WebApi/Models/Auth/ChangePasswordModel.cs
> +public sealed record ChangePasswordModel
@fabiomaistro I would suggest to rename all those "Model" into "Request". They are used only to receive data from the client app

2023-03-01 09:16 UTC, fabiomaistro requested changes

2023-03-01 11:17 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.WebApi/Models/Auth/ChangePasswordModel.cs
> +public sealed record ChangePasswordModel
done

2023-03-01 11:17 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.WebApi/Models/TFA/EnableTfaModel.cs
> +public class EnableTfaModel
fixed

2023-03-01 11:27 UTC, fabiomaistro requested changes

2023-03-01 11:27 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.WebApi/Requests/TFA/EnableTfaModel.cs
> +public sealed record EnableTfaModel
Should this be `EnableTfaRequest`?

2023-03-01 11:29 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.WebApi/Requests/TFA/EnableTfaModel.cs
> +public sealed record EnableTfaModel
Shame on me. Yes. Fixed.

2023-03-01 11:31 UTC, fabiomaistro approved these changes

2023-03-01 11:44 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.WebApi/Helpers/AppLinkGenerator.cs
> -        var url = _linkGenerator.GetUriByPage(
@fabiomaistro that's another logic that is missing, just FYI

2023-03-01 11:45 UTC, andriikaplanovskyi approved these changes

2023-03-01 11:45 UTC, merged