Hide unhandled exception info to the user on Api request failure
onebeyond/onebeyond-studio-obelisk pull request #26
Opened 2023-03-24 16:26 UTC by pn8quintero

Prevent displaying information about an unhandled exception (Stack trace, etc...) to an user when an API request fails with an unhandled exception

## Description
- Added support for handling `ArgumentException` on `ExceptionHandlingExtensions.cs`
- `UnhandledExceptionLoggingExtension` has been renamed to `UnhandledExceptionExtension`, and in addition to log the exception it sets up the request so that information about the exception is hidden to the user

2023-03-25 18:13 UTC, fabiomaistro commented
Reminder: Need to check if exceptions are shown only in dev mode

2023-03-29 15:47 UTC, fabiomaistro requested changes

2023-03-30 09:01 UTC, andriikaplanovskyi approved these changes

2023-04-03 10:58 UTC, fabiomaistro approved these changes

2023-04-03 10:58 UTC, merged