UI Message on Lockout
onebeyond/onebeyond-studio-obelisk pull request #77
Opened 2023-06-07 13:13 UTC by PeterBeyond

Counterpart to https://github.com/onebeyond/onebeyond-studio-obelisk-fe-syncfusion/compare/uiMessageOnLockout?expand=1

2023-06-07 16:33 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Application/CommandHandlers/SignInHandler.cs
> +                SignInStatus.Failure);
Guys, I'm not sure I understand those changes. Authentication is a separate Domain, and that's how it informs the calling side (our Web API) what happened. If WebAPI does not want to reveal the reason of unsuccess to the end user, it should be done on WebAPI level, not in Authentication.  Also, this reason ("invalid user name or password" and the exception below) - that's what I'd expect we to log on WebAPI level, not just "oh, something has failed" (See PR #76 ). Because when the client comes back to us with questions, we will not be able to understand and explain what has actually happened.

2023-06-07 16:46 UTC, fabiomaistro requested changes

2023-06-07 16:46 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Application/CommandHandlers/SignInHandler.cs
> +                SignInStatus.Failure);
Agree, we can remove the reason from here, but it has to be logged.
If we wanted to follow your suggestion Andrii, which I don't dislike, we could do a mapping in the webapi:

SignInStatus.WrongUsernameOrPassword => WebApiSignInStatus.Failure
SignInStatus.Failure => WebApiSignInStatus.Failure

Although I'm wondering if we still need these statuses now...

2023-06-08 08:15 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Application/CommandHandlers/SignInHandler.cs
> +                SignInStatus.Failure);
I'd ask the opposite, do we still need StatusMessage now? Taking into account we're hiding them in 10 cases out of 10. What if we go this way:
- Authentication application returns SignInResult to Web API, it does not hide the reason why the authentication failed
- Web API logs SignInResult.StatusMessage
- Web API returns SignInResult.Status only:

![image](https://github.com/onebeyond/onebeyond-studio-obelisk/assets/120190898/726ff6f2-b0a1-4094-a409-237677be68f4)

![image](https://github.com/onebeyond/onebeyond-studio-obelisk/assets/120190898/865997a2-1bf4-442c-964e-c1ca24c15114)

2023-06-09 14:02 UTC, PeterBeyond commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Application/CommandHandlers/SignInHandler.cs
> +                SignInStatus.Failure);
This sounds like a good solution to me. The only thing I'd point out is that returning only SignInStatus would miss out the lockout minutes, so we'd either need to scrap that or make a different SignInResult (I'm assuming we don't want to do logging in Authentication). Thoughts?

2023-06-09 14:12 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Application/CommandHandlers/SignInHandler.cs
> +                SignInStatus.Failure);
Guys, if we're so fixed on security, why do we let intruders know for how long the account is locked?

2023-06-09 14:29 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Application/CommandHandlers/SignInHandler.cs
> +                SignInStatus.Failure);
@PeterBeyond @fabiomaistro I checked the discussion, it is ok for me to show to a user that the account is locked, but I still do not understand why we want to show for how long the account is locked. We inform a user that the account is locked. We can add "Please contact the application admin" message, but why do we need to tell them "You're locked for 10 minutes".

2023-06-09 14:58 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Application/CommandHandlers/SignInHandler.cs
> +                SignInStatus.Failure);
@andriikaplanovskyi because people want to know how long they have to wait before trying again... And, by the way, the real argument for security is to let know the user they have been locked (regardless of the time), as this means a user was found. But unless we start storing attempts, that is not solvable for now. So, showing the user for how long is not more of a problem than the other...

2023-06-09 15:09 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Application/CommandHandlers/SignInHandler.cs
> +                SignInStatus.Failure);
@fabiomaistro sorry, I've never seen other applications to inform me how long I need to wait. Only a message "Account locked, contact administrator". "People want to know" - is this our clients' requirements or is it our initiative? My understanding is the balance between security and informing user on what happened is to show them a message "the account is locked". But I'm ok with your solution guys if you think it is needed.

2023-06-09 15:22 UTC, PeterBeyond commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Application/CommandHandlers/SignInHandler.cs
> +                SignInStatus.Failure);
Naturally I'll go with whatever you two decide on, but for what it's worth I think it is useful seeing the length of the lockout, without any (known to me) security issue. Plus I've already implemented it ;-)

2023-06-13 09:46 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Application/CommandHandlers/SignInHandler.cs
> +                SignInStatus.Failure);
@PeterBeyond @fabiomaistro as I said above, I'd agree with your solution guys.

2023-06-14 10:05 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Application/CommandHandlers/SignInHandler.cs
> +                SignInStatus.Failure);
Uncle @fabiomaistro, any decision on this topic?

2023-06-15 13:13 UTC, fabiomaistro approved these changes

2023-06-15 13:13 UTC, merged