Add linting to the workflow
onebeyond/onebeyond-studio-obelisk pull request #8
Opened 2023-01-06 17:02 UTC by nickskliar-davies

I think this should work.

2023-01-06 17:31 UTC, andriikaplanovskyi requested changes

2023-01-06 17:31 UTC, andriikaplanovskyi commented on .github/workflows/check-pr.yaml
> +      - name: "Lint"
Shall we add more meaningful name here, to clearly understand what we're doing, like for other steps?
name:  "Run Front End Code Analysis"
?

2023-01-06 17:31 UTC, andriikaplanovskyi commented on .github/workflows/check-pr.yaml
> +
@fabiomaistro @nickskliar-davies guys, just a reminder, I think we're missing a step here that compiles the WebUI (and WebApi front-end as well).

2023-01-06 17:35 UTC, nickskliar-davies commented on .github/workflows/check-pr.yaml
> +      - name: "Lint"
Can do - but it's not really a code analysis, it is just linting.

2023-01-06 17:39 UTC, nickskliar-davies commented on .github/workflows/check-pr.yaml
> +
From what @dcsl-alexis was saying - I thought WebApi frontend was getting deleted, hence why I didn't bother even applying the linting to it.

We should probably do `npm install`, `npm run lint`, `npm run build-debug` to pre PR?

2023-01-06 17:41 UTC, andriikaplanovskyi commented on .github/workflows/check-pr.yaml
> +      - name: "Lint"
@nickskliar-davies, sorry, my bad English knowledge, I thought "lint" was actually a noun, name of the tool we're executing. Shall we  name it "Lint Web.UI" then? To be more precise on what we're doing.

2023-01-06 17:43 UTC, nickskliar-davies commented on .github/workflows/check-pr.yaml
> +      - name: "Lint"
Lint is also a noun - isn't English wonderful. "Lint" is the fluff that comes out of your pockets, or your tumble dryer. "Linting" is so called, because it's small stuff that no-one should really care about. Yeah, `Lint Web.UI` sounds fine.

2023-01-06 17:44 UTC, nickskliar-davies commented on .github/workflows/check-pr.yaml
> +
I can try and sort this Monday?

2023-01-06 17:46 UTC, andriikaplanovskyi commented on .github/workflows/check-pr.yaml
> +
I suspect we need an analog of this:

![image](https://user-images.githubusercontent.com/120190898/211068430-ef9af91c-1dfd-4cd0-853f-405a701b8c3b.png)

and this

![image](https://user-images.githubusercontent.com/120190898/211068865-a76cf5bb-9afb-4586-9554-57071bd03781.png)

or shall we add those in a sep PR? thoughts?
cc  @fabiomaistro?

2023-01-06 17:47 UTC, andriikaplanovskyi commented on .github/workflows/check-pr.yaml
> +
> I thought WebApi frontend was getting deleted, hence why I didn't bother even applying the linting to it.

totally agree on that, no need may be in building and linting WebAPI. We just need to build and lint the Web.UI

2023-01-06 17:48 UTC, andriikaplanovskyi commented on .github/workflows/check-pr.yaml
> +
> I can try and sort this Monday?

sure, no rush.

2023-01-09 10:31 UTC, nickskliar-davies commented on .github/workflows/check-pr.yaml
> +
I think we want "install" and "build", but we don't want "publish".

We'll need it for projects, but my understanding is we'll still be doing client projects in Azure Devops - so "publish" will be done in there.

Also, I don't think you want `dotnet publish`, as the "static web-app" should work with `index.html` and `*.bundle.js` by itself, from memory? You just need a file copy to blob storage.

2023-01-09 10:46 UTC, nickskliar-davies commented on .github/workflows/check-pr.yaml
> +
Done - I've made it a separate step, so that lint can be skipped if necessary.

2023-01-09 10:55 UTC, andriikaplanovskyi approved these changes

2023-01-09 10:55 UTC, merged