User SecurityStamp validation added
onebeyond/onebeyond-studio-obelisk pull request #99
Opened 2023-06-26 12:41 UTC by andriikaplanovskyi

Added user SecurityStamp validation to expire all existing authentication cookies for a user if they logged out.

2023-06-26 12:42 UTC, andriikaplanovskyi commented
@fabiomaistro please do not complete until Wednesday, as @dcsl-alexis needs this issue on QA for demo purposes.

2023-06-28 17:15 UTC, fabiomaistro requested changes

2023-06-28 17:15 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Application/DependencyInjection/ServiceCollectionExtensions.cs
> +            options.ValidationInterval = TimeSpan.FromSeconds(10);
I'm not sure on why we are changing this, can you explain @andrii-kaplanovskyi ?

2023-06-29 08:02 UTC, andriikaplanovskyi commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Application/DependencyInjection/ServiceCollectionExtensions.cs
> +            options.ValidationInterval = TimeSpan.FromSeconds(10);
The default validation interval is 30 minutes. We need to do it (validate security stamps) quicker.

2023-06-29 08:19 UTC, fabiomaistro requested changes

2023-06-29 08:19 UTC, fabiomaistro commented on src/OneBeyond.Studio.Obelisk.Authentication/OneBeyond.Studio.Obelisk.Authentication.Application/DependencyInjection/ServiceCollectionExtensions.cs
> +            //Every time we logout we update the user security stamp to make sure that all existing auth cookies are invalidated
I would put a different comment saying:
`// Decrease the default interval between security stamp validations from 30 minutes to 1 minute`

2023-06-29 08:21 UTC, fabiomaistro approved these changes

2023-06-29 08:47 UTC, merged